### ISSUE TITLE
Cannot download ChefClient - no internet connectivity from our VMs

### ISSUE THREAD

**Issue by CaseyBurnsSv** [chef-partners/azure-chef-extension#124]
We have been using this plugin for about a year, I tried to use it for a new VM today. It failed because our servers have no outbound internet connectivity. The previous version worked because the ChefClient was included in the plugin package.

I can see the code change in Install-ChefClient now tries to download the ChefClient from http://www.chef.io.

What do you suggest?

**Comment by NimishaS** [comment]
@CaseyBurnsSv , `azure-chef-extension` has started using `Omnitruck` for downloading chef package since release `1210.12.5.1000` (https://github.com/chef-partners/azure-chef-extension/blob/master/CHANGELOG.md#release-12101251000-20151027).
The reason for this change was to decouple the version of the extension from chef-client's version. Earlier we had to publish the extension for every chef-client release.
You can pin your extension version to `1210.12.4.1` or earlier if you need to avoid internet connectivity, but this gives you an older version of chef-client i.e. `12.4.1`. It is recommended to use the latest version of the extension to get the latest features.

**Comment by CaseyBurnsSv** [comment]
Thanks for the reply. 

How do I pin via Azure Powershell?

Are there plans to add support for changing where the package is sourced from? I.e. UNC share on Windows would be very nice.

**Comment by NimishaS** [comment]
@CaseyBurnsSv, you can use `-Version` option in case you are using `Set-AzureVMChefExtension` ASM command.
If you are not using `Set-AzureVMChefExtension` command, please specify the command which you are using.

**Comment by NimishaS** [comment]
@CaseyBurnsSv , is your issue resolved?
