### ISSUE TITLE
is this where it comes from?

### ISSUE THREAD

**Issue by chlsmith** [chef-partners/azure-chef-extension#129]
is this where MS pulls the Chef Extension from every time I install the extension as part of an ARM template?   This is just a general question, but it's something that's highly important to folks behind proxies or whatever.

On another note, what version of the Chef Client is the most recent within the extension?   When I push mine, I'm getting version 12.3, which is really old, and I want at least 12.7 to use some of the better DSC capabilities.   12.9 would be ideal.    What version of the extension would I need to use to do that, since it appears that you're extension version is not the same as the client version?

**Comment by NimishaS** [comment]
@chlsmith , yes Chef Extensions are published in the MS Azure PIR from here only. Azure pulls the extension from it's PIR. 
Latest version of published extension is `1210.12.102.1000`. It will, by default, pull the latest version of `chef-client` i.e. `12.9.41` since the version of extension and chef-client are decoupled now.
Which version of the extension are you using currently?

**Comment by chlsmith** [comment]
I always seem to get version 12.3.   In my ARM template, should I specify 1210.12.102.1000 in the extension section?   I've tried and it the template kept puking on me.

**Comment by NimishaS** [comment]
@chlsmith , please specify `1210.12` in the `typeHandlerVersion` of the extension section. It will pick up the latest version.

**Comment by NimishaS** [comment]
@chlsmith , any updates here?

**Comment by NimishaS** [comment]
@chlsmith , is your issue resolved?

**Comment by NimishaS** [comment]
Closing this issue as there are no updates on this. @chlsmith please feel free to contact if any help required here.
