### ISSUE TITLE
Error creating Ubuntu VM in ARM mode: typeHandlerVersion is invalid

### ISSUE THREAD

**Issue by matkam** [chef-partners/azure-chef-extension#140]
I'm trying to create a Ubuntu Linux VM in ARM mode with `knife azurerm` but I get the following error
```The value of parameter typeHandlerVersion is invalid. (Code: InvalidParameter)```
Any idea what a valid parameter is here?

**Comment by Vasu1105** [comment]
@matkam I guess you are trying this with master branch since we yet not released the ARM feature for the knife azure. Could you kindly provide us the command with extended logs -VV option that you are trying and what all knife.rb settings you did for running the command in ARM mode. This will help us to reproduce the error.

**Comment by matkam** [comment]
@Vasu1105 ah yes, sorry, I posed this on the wrong repository. I'll move this issue over there.
