### ISSUE TITLE
Support bootstrap_version for Windows Installs

### ISSUE THREAD

**Issue by sean-horn** [chef-partners/azure-chef-extension#175]
The Azure Chef Extension should support specifying a version of the chef-client other than the most recent when running on Windows, just like Linux.  In this way, it is possible to work around issues in the most recent releases.

Related to https://github.com/chef-partners/azure-chef-extension/issues/81

**Comment by Aliasgar16** [comment]
@sean-horn As of now we cannot add support for `bootstrap_version` option for `Windows` platform because the source from where we read the `bootstrap_version` value while `chef-client` installation process is the `*.settings` file and we have observed that this file does not exist on `Windows` platform during the installation process as against to the `Linux` platform where the file is present during the installation process, because of which we are unable to fetch the `bootstrap_version` value from the `*.settings` file during the installation process on `Windows` platform and hence the option is not supported their.

**Comment by sean-horn** [comment]
@Aliasgar16 I'm proposing that the windows version can know how to get a chef-client version other than the latest, because it knows how to get the latest at https://github.com/chef-partners/azure-chef-extension/blob/master/ChefExtensionHandler/bin/chef-install.psm1#L44

The specific version can be specified by supplying the `-v` option to the install.ps1 script 
just as in https://github.com/chef-partners/azure-chef-extension/blob/master/ChefExtensionHandler/bin/chef-install.sh#L81

Whatever is needed to get a custom chef-client package version into the Azure extension from the outside to match the linux functionality is ok by me. If that is some config file other than *.settings, that will work.

**Comment by Aliasgar16** [comment]
@sean-horn Whatever options (public and private config) user can pass (including the `bootstrap_version` option) to the extension (through tools like `knife-azure`, `azure-xplat-cli` and `azure-powershell`) gets set in `*.settings` file, but as I said this file is not available on `Windows` platform during the installation phase. To pass the version to the https://github.com/chef-partners/azure-chef-extension/blob/master/ChefExtensionHandler/bin/chef-install.psm1#L44 script we first the need the source from where the user provided version can be fetched.

**Comment by NimishaS** [comment]
To summarize this, in order to fix this issue we need Microsoft to make some changes in the `Azure Extension` since `*.settings` file is available for linux before `install.sh` script runs, hence we are able to pick the version. But for windows this file isn't available before `install.ps1` script runs.
@sean-horn , we will follow up with Microsoft to understand why is there a difference in the behavior of `Azure Extension` for linux and windows. Meanwhile we'll try to find some alternative too if possible from our end.

**Comment by btm** [comment]
We moved the installation to the enable phase on Windows in https://github.com/chef-partners/azure-chef-extension/pull/181 to allow us to consume the `n.settings` file there. This has been tested and should be published soon in https://github.com/chef-partners/azure-chef-extension/pull/182, then we will add support to tools like `knife-azure` to use it.

**Comment by NimishaS** [comment]
@sean-horn , this issue has been resolved for `Windows 2012R2` in latest extension `1210.12.107.1000`. Please note that this functionality is still not supported for `Windows 2008`.

Please check and confirm if it unblocks you.
