### ISSUE TITLE
Extension installation completed but the Chef was not installed properly

### ISSUE THREAD

**Issue by benjamenMSFT** [chef-partners/azure-chef-extension#258]
Extension installation completed but the Chef was not installed properly
- extension should only succeed if converge action succeeds 
- if converge fails, extension should report details of the failure

**Comment by Vasu1105** [comment]
@benjamenMSFT Do you mean here that you have something in relation to your cookbook is not worked properly or chef-client installation itself failed?

**Comment by stuartpreston** [comment]
@benjamenMSFT We cannot wait for the first converge to report success because often it's many times longer than the VM Extension framework allows (15 minutes).  We are modifying the extension to ensure that we report success or failure to register the node with the server.  What happens after that will not be reported back to the extension framework (there is no mechanism in the Azure extension framework to report on detailed failures outside the extension such as converge failures).

**Comment by stuartpreston** [comment]
The changes suggested above are available in all regions now, type version 1210.13.  Specifically, we will complete one execution of Chef Client before reporting status.
