### ISSUE TITLE
[Security] Extension leaks sensitive information

### ISSUE THREAD

**Issue by tmaierACN** [chef-partners/azure-chef-extension#73]
![chefextensionerror 003](https://cloud.githubusercontent.com/assets/11663779/10165423/884dc69c-66bf-11e5-96ca-691ff3fa63ec.png)

Just tried to use the Chef Extension. The extension leaked a private key to the Azure Portal and did not provide a useful error message. We are using CentOS.

**Comment by Vasu1105** [comment]
@tmaierACN  we are trying to reproduce this issue but no luck till now, could you please give more details about it i.e. like Are you using azure powershell cmdlet ? What things are you trying ? etc

**Comment by tmaierACN** [comment]
This is how we tried to use the extension on CentOS:


```ps
# Create cloud services
New-AzureService -ServiceName "service_name" -Location "West Europe";

# Create storage account
New-AzureStorageAccount -StorageAccountName "storage_account" -Location "West Europe";

# Create VM
$image="5112500ae3b842c8b9c604889f8753c3__OpenLogic-CentOS-71-20150605";
$vm1=New-AzureVMConfig -Name "vm_name" -InstanceSize "Large" -ImageName $image;
$vm1 | Add-AzureProvisioningConfig -Linux -LinuxUser "user" -Password "password";
$vm1 | Set-AzureSubnet "subnet_name";
New-AzureVM -ServiceName "service_name" -VMs $vm1 -VNetName "vnet_name";

# Add extension
$vm=Get-AzureVM -ServiceName $svcname -Name $vmname;
Set-AzureVMExtension -VM $vm -ExtensionName 'LinuxChefClient' -Publisher 'Chef.Bootstrap.WindowsAzure' -Version 1210.12 -PublicConfigPath 'C:\Users\user\project\.chef\publicconfig.config' -PrivateConfigPath 'C:\Users\user\project\azure-resources\.chef\privateconfig.config';
$vm | Update-AzureVM;
```

Our `publicconfig.config` file

```json
{
  "client_rb": "chef_server_url \"https://url/to/chef/server\"\nencrypted_data_bag_secret \"/etc/chef/encrypted_data_bag_secret\"\nvalidation_client_name \"validator\"",
  "runlist":"role[role]",
  "autoUpdateClient":"true",
  "deleteChefConfig":"false",
  "bootstrap_options": {
    "chef_server_url":"https://url/to/chef/server",
    "validation_client_name":"the-validator"
  }
}
```

the privateconfig contained the content of the validation.pem.


We were not able to bootstrap successfully with the extension.

**Comment by adamedx** [comment]
@tmaierACN, can you repro the key leak when you do not specify a runlist? If not, that means the problem is specific to your Chef run. If that key is being output as part your Chef recipe executing, you can tell Chef to treat that as "sensitive" using the `sensitive` attribute of the resource: https://docs.chef.io/resource_common.html. An excerpt:

> sensitive	
>  Ruby Types: TrueClass, FalseClass
>
> Ensure that sensitive resource data is not logged by the chef-client. Default value: false. This > property only applies to the execute, file and template resources.

**Comment by tmaierACN** [comment]
To be honest, I would be interested in one example where this really works. Is the configuration above correct? Why was the bootstrap not successful?

**Comment by adamedx** [comment]
@tmaierACN, we've validated this with:

* `knife-azure`
* Azure PowerShell SDK: `set-AzureChefVMExtension`
* Azure xplat sdk: `azure vm extension set-chef` command

It looks like you're using an ARM template, my guess is that you have directly specified the contents of the key file rather than escaping it so that it can be expressed as JSON in the template (e.g. the key file has newlines, and those must be escaped when placed into the template). I'm guessing that's why your bootstrap is failing here (and why it works fine with the other tools which automatically escape any parameters).

We're working on an example that makes it clear how to do this.

**Comment by adamedx** [comment]
Clarification @tmaierACN: you should use `set-azurevmchefextension` instead of `set-azurevmextension`. The former you can just point to your validator key file, the latter requires you to provide particularly formatted data and is more difficult to use. I think that will address the problem.

**Comment by siddheshwar-more** [comment]
@tmaierACN  you can refer README https://github.com/chef-partners/azure-chef-extension#azure-chef-extension for example.
