### ISSUE TITLE
Chef extension is installing version 12.5.1. How is this possible?

### ISSUE THREAD

**Issue by aarsan** [chef-partners/azure-chef-extension#81]
If the latest release of this extension is 12.10.12.4.1000, why is version 12.5.1 of the chef-client being installed?

**Comment by adamedx** [comment]
@aarsan, it's correct that previously there was a link to the extension's version number (e.g. 1210.12.5.1000) and the version of Chef Client (e.g. 12.4.1), but due to recent changes the extension now defaults to installing the latest version of Chef Client. We're adding in the ability for the user to pick a specific version of the client to `knife-azure` and eventually to all CLI tools (e.g. the Azure PowerShell SDK and Azure xplat tools).

The key reason this change was made is that originally we included the actual packages for chef-client in the extension itself, which meant we had to publish a new extension with each release. As chef-client releases become more frequent, this becomes cumbersome for all involved, especially since Azure places a limit on the # of simultaneously published extension versions (around 15) and the publishing process has to manage old versions.

Ideally then the extension version only changes when the extension itself, which is responsible for installing, updating, removing, and configuring chef-client on Azure nodes, needs to change.

Note that the versioning scheme will change in the future to avoid the implication that the chef-client and extension versions are linked.

**Comment by NimishaS** [comment]
@aarsan , extension 1210.12.100 has been published where extension version and `chef-client` version are decoupled and you can specify `chef-client` version for `ubuntu` and `centos`.
Please refer https://github.com/chef-partners/azure-chef-extension/issues/75#issuecomment-158864842

**Comment by NimishaS** [comment]
With the latest linux extension `1210.12.101.1001`, `chef-client's` version can be passed as `bootstrap_version` for `ubuntu` and `centos`.
For windows, the latest version of chef-client gets installed. Latest extension version is `1210.12.101.1000`.
Closing this issue. Please feel free to re-open if you still face the issue.
